'use strict';
const assert = require('node:assert/strict');
const create = require('./security-harness');
let passed = 0;
function test(name, fn) { fn(); passed++; console.log('PASS ' + name); }
function ready() { const h = create(); h.setup(); return h; }
function snapshot(h) { return JSON.stringify({ sheets: h.book.sheets, writes: h.writes, pending: h.props.ACCESS_UPDATE_PENDING }); }
function deniedWithoutWrites(h, payload) { const before = snapshot(h); const result = h.call('access.save', payload); assert.equal(result.ok, false); assert.equal(snapshot(h), before); }
function access(email, scopeId, more) { return Object.assign({email, name:'Sample person', roleKey:'site', scopes:[{scopeId, primary:true, status:'active'}]}, more); }

test('unconfigured setup refuses without managed-sheet writes', () => { const h=create(); delete h.props.WORKSPACE_DOMAIN; assert.throws(()=>h.sandbox.setupWorkspace_(), /E_FORBIDDEN/); assert.equal(h.book.order.length,0); });
test('unknown and wrong effective identities cannot self-provision', () => { const h=create(); h.switchUser('unknown@example.org'); assert.throws(()=>h.sandbox.setupWorkspace_(), /E_FORBIDDEN/); h.switchUser('admin@example.org'); h.sandbox.Session.getEffectiveUser=()=>({getEmail:()=> 'other@example.org'}); assert.throws(()=>h.sandbox.setupWorkspace_(), /E_FORBIDDEN/); assert.equal(h.book.order.length,0); });
test('ready installation never grants an unknown caller', () => { const h=ready(), before=snapshot(h); h.switchUser('unknown@example.org'); assert.throws(()=>h.sandbox.setupWorkspace_(), /E_FORBIDDEN/); assert.equal(snapshot(h),before); });
test('test seeding cannot bootstrap an empty installation', () => { const h=create(); assert.throws(()=>h.sandbox.seedTestData_(), /E_FORBIDDEN/); assert.equal(h.book.order.length,0); });
test('populated unmanaged baseline needs explicit migration', () => { const h=create(); const sheet=h.book.insertSheet('Users'); sheet.getRange(1,1,1,1).setValues([['email']]); assert.throws(()=>h.sandbox.setupWorkspace_(),/migration/); assert.equal(h.props.INSTALLATION_STATE,undefined); });
test('interrupted initial creation resumes with stable IDs and one administrator', () => { const h=create(), original=h.sandbox.ensureManagedSheet_; let calls=0; h.sandbox.ensureManagedSheet_=spec=>{ if(++calls===5)throw Error('injected'); return original(spec); }; assert.throws(()=>h.sandbox.setupWorkspace_(),/injected/); const id=h.props.INSTALLATION_ID; h.sandbox.ensureManagedSheet_=original; h.sandbox.setupWorkspace_(); assert.equal(h.props.INSTALLATION_ID,id); assert.equal(h.rows('Users').length,1); assert.equal(h.rows('UserScopes').length,1); });
test('initial property interruptions resume from the same installation receipt', () => { for(const key of ['INSTALLATION_RECEIPT','INSTALLATION_ID','INSTALLER_EMAIL','INSTALLER_USER_ID','INSTALLATION_STATE']) { const h=create(), original=h.sandbox.PropertiesService.getScriptProperties; h.sandbox.PropertiesService.getScriptProperties=()=>{const p=original();return {getProperty:p.getProperty,setProperty:(k,v)=>{p.setProperty(k,v);if(k===key)throw Error('injected');return p;}};};assert.throws(()=>h.sandbox.setupWorkspace_(),/injected/);const receipt=h.props.INSTALLATION_RECEIPT;h.sandbox.PropertiesService.getScriptProperties=original;h.sandbox.setupWorkspace_();assert.equal(h.props.INSTALLATION_RECEIPT,receipt);assert.equal(h.rows('Users').length,1);assert.equal(h.rows('UserScopes').length,1);} });
test('administrative roles cannot be granted site-only scope', () => {const h=ready(),id=h.sandbox.findAccessUnitByName_('site','Harbor North').unitId;deniedWithoutWrites(h,access('restricted@example.org',id,{roleKey:'admin'}));});
test('existing narrow administrative grants fail closed', () => {const h=ready(),id=h.sandbox.findAccessUnitByName_('site','Harbor North').unitId;h.sandbox.appendRow_('Users',{userId:'restricted',email:'restricted@example.org',active:true,roleKey:'admin'});h.sandbox.appendRow_('UserScopes',{userScopeId:'restricted-site',userId:'restricted',scopeId:id,scopeType:'site',status:'active'});assert.equal(h.sandbox.resolveAccessUser_('restricted@example.org'),null);});
test('normalized full emails do not collide when punctuation differs', () => { const h=ready(), id=h.sandbox.findAccessUnitByName_('site','Harbor North').unitId; const a=h.call('access.save',access('a.b@example.org',id)),b=h.call('access.save',access('a-b@example.org',id)); assert.equal(a.ok,true);assert.equal(b.ok,true);assert.notEqual(a.item.userId,b.item.userId);assert.match(a.item.userId,/^user_[0-9a-f-]{36}$/); });
test('punctuation-different organization names receive distinct stable IDs', () => { const h=ready(); for(const site of ['Team.A','Team-A'])assert.equal(h.call('site.save',{item:{site,region:'North',active:true}}).ok,true); const a=h.sandbox.findAccessUnitByName_('site','Team.A'),b=h.sandbox.findAccessUnitByName_('site','Team-A'); assert.notEqual(a.unitId,b.unitId);h.sandbox.syncOrganizationUnitsFromSites_('admin@example.org');assert.equal(h.sandbox.findAccessUnitByName_('site','Team.A').unitId,a.unitId); });
test('revoked user is denied immediately without clearing cache', () => { const h=ready(); h.switchUser('site@example.org'); assert.equal(h.call('bootstrap').user.known,true); const row=h.sandbox.findRow_('Users','email','site@example.org');row.active=false;h.sandbox.writeRowAt_('Users',row._row,row);assert.equal(h.call('intake.list').code,'E_FORBIDDEN'); });
test('inactive role is denied immediately', () => { const h=ready(); const role=h.sandbox.findRow_('Roles','roleKey','site');role.active=false;h.sandbox.writeRowAt_('Roles',role._row,role);h.switchUser('site@example.org');assert.equal(h.call('intake.list').code,'E_FORBIDDEN'); });
test('inactive ancestor removes descendant scopes', () => { const h=ready(), region=h.sandbox.findAccessUnitByName_('region','North');region.active=false;h.sandbox.writeRowAt_('OrganizationUnits',region._row,region);h.switchUser('site@example.org');assert.equal(h.call('intake.list').code,'E_FORBIDDEN'); });
test('duplicate normalized emails fail closed', () => { const h=ready(), row=h.sandbox.findRow_('Users','email','site@example.org');h.sandbox.appendRow_('Users',Object.assign({},row,{userId:'another',email:' SITE@example.org '}));h.switchUser('site@example.org');assert.equal(h.call('intake.list').code,'E_FORBIDDEN'); });
test('duplicate user IDs fail closed', () => { const h=ready(), row=h.sandbox.findRow_('Users','email','site@example.org');h.sandbox.appendRow_('Users',Object.assign({},row,{email:'another@example.org'}));h.switchUser('site@example.org');assert.equal(h.call('intake.list').code,'E_FORBIDDEN'); });
test('outside-domain users cannot be granted access', () => { const h=ready();deniedWithoutWrites(h,access('outside@example.net',h.sandbox.findAccessUnitByName_('site','Harbor North').unitId)); });
test('invalid role and nonexistent scope perform zero writes', () => { const h=ready();deniedWithoutWrites(h,access('person@example.org','missing'));deniedWithoutWrites(h,access('person@example.org','ORG-ROOT',{roleKey:'unknown'})); });
test('invalid date and status fail before any first valid scope is written', () => { const h=ready(), id=h.sandbox.findAccessUnitByName_('site','Harbor North').unitId;for(const invalid of [{startsOn:'2026-02-30'},{startsOn:'2026-01-01T12:00:00Z'},{status:'enabled'}])deniedWithoutWrites(h,access('person@example.org',id,{scopes:[{scopeId:id,status:'active'},Object.assign({scopeId:id},invalid)]})); });
test('scope ID belonging to another person cannot be stolen', () => { const h=ready(), target=h.sandbox.findRow_('Users','email','site@example.org'), scope=h.sandbox.accessScopesForUser_(target.userId,true)[0];deniedWithoutWrites(h,access('attacker@example.org',scope.scopeId,{scopes:[scope]})); });
test('omitted scopes preserve existing access without root fallback', () => { const h=ready(), before=h.sandbox.findRow_('Users','email','site@example.org'), scopes=h.sandbox.accessScopesForUser_(before.userId,true);assert.equal(h.call('access.save',{email:before.email,name:'Renamed sample',roleKey:'site'}).ok,true);assert.deepEqual(h.sandbox.accessScopesForUser_(before.userId,true).map(s=>s.scopeId),scopes.map(s=>s.scopeId)); });
test('new users require an explicit access area', () => { const h=ready();deniedWithoutWrites(h,{email:'person@example.org',roleKey:'admin',name:'Sample'}); });
test('role downgrade can explicitly deactivate a broader owned grant', () => {const h=ready(),person=h.sandbox.findRow_('Users','email','regional@example.org'),scope=h.sandbox.accessScopesForUser_(person.userId,true)[0],id=h.sandbox.findAccessUnitByName_('site','Harbor North').unitId;const result=h.call('access.save',{email:person.email,name:person.name,roleKey:'site',scopes:[Object.assign({},scope,{status:'inactive',primary:false}),{scopeId:id,status:'active',primary:true}]});assert.equal(result.ok,true);assert.deepEqual(Array.from(h.sandbox.resolveAccessUser_(person.email).scopeSites),['Harbor North']);});
test('last usable root administrator cannot lose role or scope', () => { const h=ready();deniedWithoutWrites(h,{email:'admin@example.org',roleKey:'admin',active:false});deniedWithoutWrites(h,{email:'admin@example.org',roleKey:'admin',scopes:[{scopeId:'ORG-ROOT',status:'inactive'}]}); });
test('inactive or expired secondary admin does not satisfy administrator protection', () => { const h=ready();assert.equal(h.call('access.save',access('second@example.org','ORG-ROOT',{roleKey:'admin'})).ok,true);const person=h.sandbox.findRow_('Users','email','second@example.org');const scope=h.sandbox.accessScopesForUser_(person.userId,true)[0];scope.endsOn='2000-01-01';h.sandbox.writeRowAt_('UserScopes',scope._row,scope);deniedWithoutWrites(h,{email:'admin@example.org',roleKey:'admin',active:false}); });
test('malformed secondary scope cannot substitute for the last administrator', () => { for(const mutation of [{scopeType:'site'},{startsOn:'2000-02-30'}]) {const h=ready();assert.equal(h.call('access.save',access('second@example.org','ORG-ROOT',{roleKey:'admin'})).ok,true);const person=h.sandbox.findRow_('Users','email','second@example.org');const scope=h.sandbox.accessScopesForUser_(person.userId,true)[0];Object.assign(scope,mutation);h.sandbox.writeRowAt_('UserScopes',scope._row,scope);assert.equal(h.sandbox.resolveAccessUser_('second@example.org'),null);deniedWithoutWrites(h,{email:'admin@example.org',roleKey:'admin',active:false});} });
test('role lacking app.read cannot substitute for the last administrator', () => { const h=ready();h.sandbox.appendRow_('Roles',{roleKey:'limited',active:true});h.sandbox.appendRow_('RolePermissions',{rolePermissionId:'limited-manage',roleKey:'limited',permissionKey:'admin.manage',scopeCeiling:'organization',active:true});h.sandbox.appendRow_('Users',{userId:'second',email:'second@example.org',active:true,roleKey:'limited'});h.sandbox.appendRow_('UserScopes',{userScopeId:'second-root',userId:'second',scopeType:'organization',scopeId:'ORG-ROOT',status:'active'});deniedWithoutWrites(h,{email:'admin@example.org',roleKey:'admin',active:false}); });
test('site hierarchy reassignment is blocked without writes', () => { const h=ready(), before=snapshot(h);assert.equal(h.call('site.save',{item:{site:'Harbor North',region:'South'}}).code,'E_VALIDATION');assert.equal(snapshot(h),before); });
test('pending access persistence blocks the target and permits authorized recovery', () => { const h=ready();const original=h.sandbox.operationPut_;h.sandbox.operationPut_=(name,key,row)=>{if(name==='UserScopes')throw Error('injected');return original(name,key,row);};assert.equal(h.call('access.save',access('person@example.org',h.sandbox.findAccessUnitByName_('site','Harbor North').unitId)).ok,false);assert.equal(h.sandbox.resolveAccessUser_('person@example.org'),null);assert.equal(h.call('intake.list').ok,true);assert.equal(h.props.ACCESS_UPDATE_PENDING,undefined);h.sandbox.operationPut_=original;const op=h.rows('Operations').find(row=>row.status!=='COMMITTED');h.sandbox.recoverAccessOperation_(op.operationId);assert.equal(h.sandbox.resolveAccessUser_('person@example.org').known,true); });
test('role revocation while acquiring mutation lock prevents write', () => { const h=ready();const role=h.sandbox.findRow_('Roles','roleKey','admin');h.sandbox.LockService.getScriptLock=()=>({waitLock:()=>{role.active=false;h.sandbox.writeRowAt_('Roles',role._row,role);},releaseLock:()=>{}});assert.equal(h.call('metric.save',{name:'Unauthorized',metricType:'count',direction:'higher'}).code,'E_FORBIDDEN');assert.equal(h.rows('Metrics').some(m=>m.name==='Unauthorized'),false); });
test('region cannot edit or discover whole manual metadata', () => { const h=ready();h.call('playbook.ensureDoc');h.switchUser('regional@example.org');assert.equal(h.call('bootstrap').improve.canManagePlaybook,false);for(const action of ['playbook.ensureDoc','playbook.recheck','playbook.remind'])assert.equal(h.call(action).code,'E_FORBIDDEN');const board=h.call('playbook.board');assert.equal(board.doc,null);assert.equal(board.health,null);assert.equal(h.call('goal.get',{goalId:'goal-north-screen'}).canManagePlaybook,false); });
test('the API denies inherited object properties as actions',()=>{const h=ready();for(const action of ['constructor','toString','__proto__'])assert.equal(h.call(action).code,'E_NOT_FOUND');});
test('the last durable administrator cannot become temporary',()=>{const h=ready(),person=h.sandbox.findRow_('Users','email','admin@example.org'),scope=h.sandbox.accessScopesForUser_(person.userId,true)[0],today=new Date().toISOString().slice(0,10);deniedWithoutWrites(h,{email:person.email,name:person.name,roleKey:'admin',scopes:[Object.assign({},scope,{assignmentType:'Temporary Coverage',startsOn:today,endsOn:today,reason:'Sample temporary cover',approvedBy:person.email})]});});
test('blank persisted scope status is denied',()=>{const h=ready(),person=h.sandbox.findRow_('Users','email','site@example.org'),scope=h.sandbox.accessScopesForUser_(person.userId,true)[0];scope.status='';h.sandbox.writeRowAt_('UserScopes',scope._row,scope);assert.equal(h.sandbox.resolveAccessUser_(person.email),null);});
test('formatting failure prevents ready installation and retry completes safely',()=>{const h=create(),range=h.book.insertSheet('Unrelated').getRange(1,1,1,1),proto=Object.getPrototypeOf(range),format=proto.setNumberFormat;proto.setNumberFormat=()=>{throw Error('formatting unavailable');};assert.throws(()=>h.sandbox.setupWorkspace_(),/formatting unavailable/);assert.notEqual(h.props.INSTALLATION_STATE,'ready');proto.setNumberFormat=format;h.sandbox.setupWorkspace_();assert.equal(h.props.INSTALLATION_STATE,'ready');});
test('direct mutating APIs require an explicit retry key',()=>{const h=ready(),before=JSON.stringify(h.book.sheets);for(const [action,payload] of [['metric.save',{name:'Sample',metricType:'count',direction:'higher'}],['metric.retire',{metricId:'metric-no-show'}],['goal.save',{}],['goal.retire',{}],['actual.correct',{correctionReason:'Checked'}],['site.save',{item:{site:'Sample',region:'North'}}]])assert.equal(h.sandbox.api({action,payload}).code,'E_VALIDATION');assert.equal(JSON.stringify(h.book.sheets),before);});
test('public runtime declarations expose only doGet api onOpen', () => { const fs=require('node:fs'), path=require('node:path');const names=[];for(const file of fs.readdirSync(path.join(__dirname,'../app')).filter(f=>f.endsWith('.gs')))for(const match of fs.readFileSync(path.join(__dirname,'../app',file),'utf8').matchAll(/^function\s+(\w+)\s*\(/gm))if(!match[1].endsWith('_'))names.push(match[1]);assert.deepEqual(names.sort(),['api','doGet','onOpen']); });
console.log('PASSED '+passed+' / '+passed+' security boundary scenarios');
